#pragma once

#define MAP_BASE_SIZE_X 60;
#define MAP_BASE_SIZE_Y 30;
#define MAP_BASE_START_X 0;
#define MAP_BASE_START_Y 0;
#define MAP_BASE_TUNNEL_MAX_NUMBER 50;
#define MAP_BASE_TUNNEL_MIN_LENGTH 4;
#define MAP_BASE_TUNNEL_MAX_LENGTH 10;
#define MAP_BASE_TUNNEL_MAX_TRY_NUMBER 50;